### ISSUE TITLE
Error when running Migration

### ISSUE THREAD

**Issue by djunehor** [moluwole/Bast#20]
1. When I execute `panther migration:run` I get this error: `KeyError: DB_TYPE`

When I dumped the environment variables using `os.environ()`, I saw that the values set in `.env` weren't present.

My solution was to use `python-dotenv` to load the `.env` first before trying to access the values. 

2. After resolving the first error, I encountered another error `KeyError: 'DB_PREFIX'`. I realised it's caused by the DB_PREFIX been empty in the `.env` file.
The fix is to set the DB_PREFIX as empty string i.e `DB_PREFIX=''`, but that's not efficient as some env values have to be empty e.g empty db password. The more efficient way is to use `os.getenv('KEY', '')` instead of `os.environ['KEY']`

Environment
MacOS 10.15.2
Python 3.7.5
MySQL 8.0.18

**Comment by moluwole** [comment]
@djunehor Thanks for pointing that out. This has been a wake up call for me, showing me that this project is still something interesting to work on. If you don't mind, I would love for you contribute to this project. There is a ton of work to do on this.

P.S: I stole your thunder and made a PR with your proposed fix. 😜🤪

**Comment by moluwole** [comment]
If it's not too much hassle, you can review it here: https://github.com/moluwole/Bast/pull/21

**Comment by moluwole** [comment]
Resolved.
