### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by iamhabbeboy** [moluwole/Bast#6]
create session support for Bast framework

**Comment by hamzzy** [comment]
it has been done and push sir it can handle both memory and file

**Comment by moluwole** [comment]
Cool @hamzzy could you please add a code snippet which shows how to make use of it and where it would be used? After which you should open a pull request..Thanks

**Comment by moluwole** [comment]
@hamzzy @iamhabbeboy, what do you think of the following

in controller, we use
`self.session.flash(key, value)` to add temporary session or `self.session.put(key, value)`

to access it in our `view` template, we use 
```
{% if session.has(key) %}
   <p> {{ session.get(key) }} </p>
{% endif %}
```

**Comment by moluwole** [comment]
I've modified your code a little bit @hamzzy to accomodate the changes reflected above. What do you think?

**Comment by hamzzy** [comment]
that cool i can't wait to see that i just finish my school exam on friday so that was wat made the progress so slow . but it cool

**Comment by hamzzy** [comment]
any update i have i will push

**Comment by moluwole** [comment]
Cool @hamzzy You can go through my implementation of the Session class. It's on the `session` branch. So you might need to update your repository. Thinking of adding time based session i.e. The session would expire when the time has elapsed
